# Generated by Django 4.2 on 2025-01-17 22:48

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('genre', models.CharField(choices=[('house', 'House'), ('tech_house', 'Tech House'), ('trance', 'Trance'), ('dubstep', 'Dubstep'), ('drum_and_bass', 'Drum and Bass'), ('techno', 'Techno'), ('electro', 'Electro'), ('progressive_house', 'Progressive House'), ('chillout', 'Chillout'), ('other', 'Other')], default='other', max_length=50)),
                ('audio_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location=''), upload_to='audio_files/')),
                ('album_cover', models.ImageField(blank=True, default='../default_cover', storage=django.core.files.storage.FileSystemStorage(location=''), upload_to='album_covers/')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('ratings_count', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tracks', to='profiles.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
