# Generated by Django 5.1.4 on 2025-01-07 12:50

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='album_cover',
            field=models.ImageField(blank=True, default='../default_cover', storage=django.core.files.storage.FileSystemStorage(location=''), upload_to='album_covers/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=''), upload_to='audio_files/'),
        ),
    ]
