# Generated by Django 4.2 on 2025-01-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_alter_track_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='genre',
            field=models.CharField(choices=[('house', 'House'), ('tech_house', 'Tech House'), ('trance', 'Trance'), ('dubstep', 'Dubstep'), ('drum_and_bass', 'Drum and Bass'), ('techno', 'Techno'), ('electro', 'Electro'), ('progressive_house', 'Progressive House'), ('chillout', 'Chillout'), ('other', 'Other')], max_length=50),
        ),
    ]
