# Generated by Django 5.1.4 on 2025-01-15 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
        ('tracks', '0003_alter_track_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tracks', to='profiles.profile'),
        ),
    ]
