# Generated by Django 4.2 on 2025-01-21 10:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_alter_track_album_cover_alter_track_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='audio'),
        ),
    ]
