# Generated by Django 4.2 on 2025-01-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0007_alter_track_album_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='album_cover',
            field=models.CharField(default='../default_profile_bp5fwp', editable=False, max_length=1024),
        ),
    ]
