# Generated by Django 4.2 on 2025-01-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0010_alter_track_album_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='album_cover',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dmylma7bf/image/upload/v1736220045/s4eqgf6v116nszs9vgqm.png', upload_to='album_covers/'),
        ),
    ]
