# Generated by Django 4.2 on 2025-01-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='tracks.track'),
        ),
    ]
