# Generated by Django 4.2 on 2025-01-07 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='dj_name',
            new_name='name',
        ),
    ]
