# Generated by Django 5.1.4 on 2025-01-08 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_dj_name_profile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='dj_name',
        ),
    ]
