# Generated by Django 5.1.4 on 2025-01-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dmylma7bf/image/upload/v1735822416/default_profile_bp5fwp.jpg', upload_to='images/'),
        ),
    ]
